// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stock} from '../models';

export function GetStockData(arg1:string):Promise<stock.StockData>;
