// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {stock} from '../models';

export function GetSettings():Promise<settings.Settings>;

export function GetStockData(arg1:string):Promise<stock.StockData>;

export function UpdateColors(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;

export function UpdateTheme(arg1:settings.Theme):Promise<void>;
